[WIP] X.H.DynamicLog: Start recommending poperty-based logging
xmonad/xmonad-contrib pull request #408
Opened 2020-11-18 12:02 UTC by slotThe

### Description

Stop recommending pipes as the best/first thing to do and instead recommend
property based logging for all bars that support it.  Also strongly recommend
users to use the already pre-made functions that do all of the plumbing.

Using pipes is very error-prone (see e.g. #400), so this seems like a logical
step.  

Unfortunately, how we go about spawning the status bar in this case is not quite
clear.  We can't use `spawn`, nor `safeSpawn`, because that would spawn the
status bar again (without killing the other one first) when restarting xmonad
via `M-q`.  `spawnOnce` is also unsuited (and only used here as a placeholder)
because users expect changes to their bar configurations to take effect when
they `M-q` restart xmonad.  On IRC, we've discussed saving the PIDs somewhere
and killing them when executing `statusBarProp`, but there was a very good
objection to that:

```
<fizzie> I'd be a little wary about something that just blindly sends signals. What if the process got killed in the meanwhile (crash or whatever), and the PID reused for something else? (Not that there's probably that great alternatives, and I'm sure it works in practice.)
```

I'm putting this up as a draft because, frankly, I've run out of ideas.

TODO: 

  - [ ] Update CHANGELOG.md

  - [ ] Find a good solution for spawning status bars  

### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [X] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

  - [ ] I updated the `CHANGES.md` file

  - [ ] I updated the `XMonad.Doc.Extending` file (if appropriate)

2020-12-14 22:40 UTC, liskin commented
@slotThe see https://github.com/xmonad/xmonad-contrib/issues/433

2020-12-18 12:35 UTC, TheMC47 commented
I opened #434 and I rebased it on top of this branch. I'm confused with what's the best thing to do git-wise: should we merge this, then I rebase the other one on top of master?

2020-12-18 12:58 UTC, slotThe commented
On Fri, Dec 18 2020 04:35, Yecine Megdiche wrote:
> I opened #434 and I rebased it on top of this branch.

Great!  I just pushed some final changes, as well as doc updates; I'll
convert this from its draft state now

> I'm confused with what's the best thing to do git-wise: should we
> merge this, then I rebase the other one on top of master?

That sounds like the way to go yes

2020-12-18 15:48 UTC, TheMC47 commented
Great, I've done that

2020-12-18 17:27 UTC, slotThe commented
@liskin @psibi This should now be ready for review, if you're inclined

2020-12-18 18:21 UTC, psibi requested changes
This is new to me, so I don't have much idea about what's going on. That being said, it LGTM. When you mention property, I'm assuming you are referring to this: https://en.wikipedia.org/wiki/X_Window_System_core_protocol#Properties

If yes, can you add that link as part of haddock ? If not, I would like to learn more about it. :-)

2020-12-18 18:21 UTC, psibi commented on XMonad/Hooks/DynamicLog.hs
> +-- status bar that supports property logging, is to use on of the following two
/s/on/one ?

2020-12-18 20:05 UTC, slotThe commented
> That being said, it LGTM. When you mention property, I'm assuming you are referring to this: https://en.wikipedia.org/wiki/X_Window_System_core_protocol#Properties
> 
> If yes, can you add that link as part of haddock ? If not, I would like to learn more about it. :-)

Yes indeed!  It literally just dumps it out to such a property, for example in my case: 

``` shell
$ xprop -root
...
_XMONAD_LOG(UTF8_STRING) = "<fc=#f8f8f2> 1:WEB</fc> <fc=#f8f8f2> 2</fc>  <box type=Top width=2 color=#8be9fd>3</box> <fc=#f8f8f2> 6:VPN</fc><fc=#ff79c6> • </fc>Full<fc=#ff79c6> • </fc><fc=#f8f8f2>[</fc><fc=#ff79c6>slot: xprop -root</fc><fc=#f8f8f2>]</fc> <fc=#bbbbbb>[</fc><fc=#bd93f9>DynamicLog.hs</fc><fc=#bbbbbb>]</fc>"
...
```

I've updated the docs with a few links (and have hopefully made it clear enough that these are supplemental, to not scare away potential users :)

2020-12-19 13:16 UTC, merged

2020-12-19 13:16 UTC, psibi commented
Thank you!

2020-12-19 16:30 UTC, psibi commented
@slotThe I migrated my xmonad + xmobar configuration to use this and it works perfectly. Thanks for the feature!

2020-12-19 18:32 UTC, liskin commented
I pushed https://github.com/xmonad/xmonad-contrib/commit/555cd7c59695ac5b53426b7070725ca1a69612d8 with a few corrections. Sorry I didn't look at this earlier. On the other hand, by just pushing it, I saved us both a back-and-forth. :-)

Anyway, a couple remarks:

https://github.com/xmonad/xmonad-contrib/blob/555cd7c59695ac5b53426b7070725ca1a69612d8/XMonad/Hooks/DynamicLog.hs#L143
^^ there's xmonadpropread in xmonad-contrib/scripts, we may clean it up and document it and link to it

https://github.com/xmonad/xmonad-contrib/commit/555cd7c59695ac5b53426b7070725ca1a69612d8#diff-2107a045a6f2cac0a766c17d80d8b0ffb94ebe4954952ccd2d9b4147da80c44cL202
I dropped the text about statusBarProp handling restarts correctly as that isn't yet true (will be fixed by @TheMC47 in #434, so this will need to be added back again).

I added another note about configuring XMonadLog and opened https://github.com/jaor/xmobar/issues/517 because it's silly that users need to do that.

2020-12-20 07:20 UTC, slotThe commented
On Sat, Dec 19 2020 10:32, Tomáš Janoušek wrote:
> I pushed
> https://github.com/xmonad/xmonad-contrib/commit/555cd7c59695ac5b53426b7070725ca1a69612d8
> with a few corrections. Sorry I didn't look at this earlier. On the
> other hand, by just pushing it, I saved us both a back-and-forth. :-)

These all look pretty good, thanks!

> https://github.com/xmonad/xmonad-contrib/blob/555cd7c59695ac5b53426b7070725ca1a69612d8/XMonad/Hooks/DynamicLog.hs#L143
> ^^ there's xmonadpropread in xmonad-contrib/scripts, we may clean it
> up and document it and link to it
>

Oh very interesting!  Didn't know that existed, I'll look into
prettifying it a bit and then linking to it (unless you want to do that
:>)

2020-12-20 09:25 UTC, liskin commented
I won't get to it, so go ahead. The locale/encoding handling in there is probably broken, too.