Add fullscreenSupport'
xmonad/xmonad-contrib pull request #476
Opened 2021-03-14 08:53 UTC by exorcist365

### Description

Add fullscreenSupport' which uses smartBorders to remove the window borders when a window goes fullscreen.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

  - [x] I updated the `CHANGES.md` file

  - [ ] I updated the `XMonad.Doc.Extending` file (if appropriate)

2021-03-14 09:11 UTC, slotThe commented
On Sun, Mar 14 2021 00:53, Joan MIlev wrote:
> Add fullscreenSupport'

May I suggest `fullscreenSupportBorder` or a similar name?  I think we
should stop with the `function'` idiom for user-facing functions.

> -- Commit Summary --
>
>   * add fullscreenSupport&#39; for autohiding window borders
>   * docs:update
>   * docs:update
>   * docs:update
>   * docs:update
>

You should probably squash those doc commits.

2021-03-16 09:09 UTC, slotThe requested changes

2021-03-17 07:03 UTC, exorcist365 commented on CHANGES.md
> +
Ah.. Ok fixed.

2021-03-17 07:22 UTC, slotThe requested changes
Almost done!

2021-03-17 07:22 UTC, slotThe commented on CHANGES.md
> +    when the window is fullscreen.
In accordance with the rest of the (now thankfully uniform) section, please use a bullet point here, e.g.

```suggestion
    - Add fullscreenSupportBorder which uses smartBorders to remove
      window borders when the window is fullscreen.
```

2021-03-17 08:50 UTC, merged

2021-03-17 08:50 UTC, slotThe commented
Actually I will just merge and correct the small doc error; thanks!

2021-03-17 11:01 UTC, exorcist365 commented
No. I thank you.