Redefined `ComplCaseSensitivity` as a proper sum type. (#509)
xmonad/xmonad-contrib pull request #520
Opened 2021-04-16 18:57 UTC by nikshalark

### Description

This is my first time submitting a pull request of any kind, so please tell me if I've done anything incorrectly.

This PR is an implementation of the suggestion in issue #509, with all relevant functions changed so as to expect the rewritten datatype. 

### Checklist

  - [✔️] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [✔️] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

  - [✔️] I updated the `CHANGES.md` file

  - [✔️] I updated the `XMonad.Doc.Extending` file (if appropriate)

2021-04-16 21:00 UTC, TheMC47 requested changes
Awesome, thank you for your contribution! :tada:  Just a few comments and we're ready to go

2021-04-16 21:00 UTC, TheMC47 commented on CHANGES.md
> +
There is already an entry for `XMonad.Prompt`, so add it there instead.

2021-04-16 21:12 UTC, geekosaur commented on XMonad/Prompt/Shell.hs
> +    "bind 'set completion-ignore-case " ++ (if b == CaseSensitive then "off" else "on") ++ "'"
Of the two, the first is more Haskelly. Eq costs more and is less idiomatic.

2021-04-17 06:05 UTC, slotThe commented on XMonad/Prompt/Shell.hs
> +    "bind 'set completion-ignore-case " ++ (if b == CaseSensitive then "off" else "on") ++ "'"
I agree, something like 

``` haskell
complCaseSensitivityCmd cs = [...]
 where
  caseSensitivity = case cs of 
    CaseSensitive   -> "off"
    CaseInsensitive -> "on"
```

would be nice!

2021-04-17 06:24 UTC, nikshalark commented
Thank you everyone for being so kind in dealing with this, especially with such a small issue. I have implemented the changes you all have requested. Unnecessary parentheses have been removed and the equality issue has been solved with a pattern match.

2021-04-17 06:29 UTC, nikshalark commented on XMonad/Prompt/Shell.hs
> +    "bind 'set completion-ignore-case " ++ (if b == CaseSensitive then "off" else "on") ++ "'"
This has been changed! Thanks for catching this, I always seem to think an Eq instance is defined no matter what I'm working on.

2021-04-17 07:23 UTC, merged

2021-04-17 07:23 UTC, slotThe commented
Thanks!