Add custom resize ratio to X.L.BinarySpacePartition
xmonad/xmonad-contrib pull request #541
Opened 2021-05-10 22:19 UTC by exorcist365

### Description

Include a description for your changes, including the motivation
behind them.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I've considered how to best test these changes (property, unit,
        manually, ...) and concluded: That it works.

  - [x] I updated the `CHANGES.md` file

  ~~- [ ] I updated the `XMonad.Doc.Extending` file (if appropriate)~~

2021-05-11 05:11 UTC, exorcist365 commented
> At a first glance, this seems like a breaking change. Any way we could avoid that?

Probably, I just don't know how.

2021-05-11 09:12 UTC, exorcist365 commented
Thank you, I will take a look!

2021-05-11 11:17 UTC, exorcist365 commented
I will reopen this when I have a better idea of how to enable the custom resize without breaking it.

2021-05-11 11:40 UTC, TheMC47 commented
@exorcist365 we can figure this out together! @liskin mentioned `PatternSynonyms`, which we can use here. What we can do is rename the constructors you added, so we don't have conflicts. Maybe `ExpandTowardsWith`? I'm bad at naming things. And then we can create a pattern for the old `ExpandTowards`:
```haskell
{-# LANGUAGE PatternSynonyms #-}

pattern ExpandTowards d = ExpandTowardsWith d 0.5
```
and only handle `ExpandTowardsWith` in the messages. Is it clear?

2021-05-12 15:17 UTC, TheMC47 commented
`ExpandTowards` are just patterns, they're not really messages. You can export them as `pattern ExpandTowards`, or by adding them to the list of constructors ( `ResizeDirectional(.., ExpandTowardsLeft)`)
https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/pattern_synonyms.html#import-and-export-of-pattern-synonyms

2021-05-12 17:01 UTC, exorcist365 commented
@TheMC47 thank you for helping me, I will proceed to pushing and reopen the pr.

2021-05-15 08:36 UTC, TheMC47 requested changes
Awesome work :tada:  I just have some minor comments.
It would be also nice if you could update the usage section to include the new constructors (maybe use them instead and add a note that `ExpandTowards x` is equivalent to `ExpandTowardsBy x 0.05`, or something similar)

2021-05-15 08:36 UTC, TheMC47 commented on XMonad/Layout/BinarySpacePartition.hs
> +          resize (MoveSplit dir) = autoSizeNth dir 0.05 b
As far as I understand how `PatternSynonyms` work, these cases are redundant as they're covered by the more general constructors

2021-05-15 08:36 UTC, TheMC47 commented on XMonad/Layout/BinarySpacePartition.hs
> +-- | Patterns to replicate the old messages
This comment is just for `ExpandTowards`. Please add a comment to each pattern, and say what it's equivalent to (e.g. `ExpandTowards L` is equivalent to `ExpandTowardsBy L 0.05`

2021-05-15 10:05 UTC, TheMC47 approved these changes
LGTM

2021-05-15 10:05 UTC, TheMC47 commented on XMonad/Layout/BinarySpacePartition.hs
> +-- ShrinkFrom x is equal to ShrinkFromBy x 0.05 and MoveSplit x is equal to MoveSplitBy x 0.05
```suggestion
-- Note that @ExpandTowards x@, @ShrinkFrom x@, and @MoveSplit x@ are
-- the same as respectively @ExpandTowardsBy x 0.05@, @ShrinkFromBy x 0.05@
-- and @MoveSplitBy x 0.05@.
```

2021-05-15 10:05 UTC, TheMC47 commented on XMonad/Layout/BinarySpacePartition.hs
> +-- | ExpandTowards x is now the equivalent of ExpandTowardsBy x 0.05
```suggestion
-- | @ExpandTowards x@ is now the equivalent of @ExpandTowardsBy x 0.05@
```

2021-05-15 10:05 UTC, TheMC47 commented on XMonad/Layout/BinarySpacePartition.hs
> +-- | ShrinkFrom x is now the equivalent of ShrinkFromBy x 0.05
```suggestion
-- | @ShrinkFrom x@ is now the equivalent of @ShrinkFromBy x 0.05@
```

2021-05-15 10:05 UTC, TheMC47 commented on XMonad/Layout/BinarySpacePartition.hs
> +-- | MoveSplit x is now the equivalent of MoveSplitBy x 0.05
```suggestion
-- | @MoveSplit x@ is now the equivalent of @MoveSplitBy x 0.05@
```

2021-05-20 09:07 UTC, TheMC47 commented
Can you please squash the commits?

2021-05-20 17:29 UTC, exorcist365 commented
> Can you please squash the commits?

Sure.

2021-05-23 15:22 UTC, slotThe approved these changes

2021-05-25 09:54 UTC, TheMC47 requested changes
One thing and this is ready to go: you need to rebase instead of merging master into your branch.  This is actually mentioned in the contributing instructions https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md#rebasing-and-squashing-commits:

> Under no circumstances should you ever merge the master branch into your feature branch. This makes it nearly impossible to review your changes and we will not accept your PR if you do this.

Once you take care of that, we'll merge this. Thank you for your contribution once again :tada:

2021-05-25 09:57 UTC, liskin commented
I'd also recommend going through https://chris.beams.io/posts/git-commit/ one more time. The "If merged, this …" commits indicate the author tried to learn about writing good commit messages, but hasn't got it yet.

2021-05-25 12:50 UTC, TheMC47 commented
The commit message is `Squash commits.` Can you please change it? You can use `git commit --amend` to edit it. I'd also kindly ask you to read the guide that was posted by liskin

2021-05-25 14:15 UTC, exorcist365 commented
I forgot to readd the changes suggested by slotThe so I will just push this.

2021-06-01 19:04 UTC, merged

2021-06-01 19:06 UTC, liskin commented
The commits needed a bit more love but I decided it'll be easier if I do the final polish and merge it.
Thanks for the contribution! :tada:

2021-06-10 15:22 UTC, exorcist365 commented
Alright, thanks!