Add a method to re-sort keys for visualSubmap
xmonad/xmonad-contrib pull request #888
Opened 2024-05-08 00:54 UTC by andwu137

### Description

I did not see any way to display the submap bindings in a different order. I created a general function that takes a sorter for the descriptions (`visualSubmapSorted`).

The change from `zipWith` to `map . zip` showed no noticeable performance effects.

### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [X] I've considered how to best test these changes (property, unit,
        manually, ...) and concluded: Manually tested; have observed no issues.

  - [X] I updated the `CHANGES.md` file

2024-05-08 01:45 UTC, geekosaur approved these changes

2024-05-08 01:45 UTC, geekosaur commented on XMonad/Actions/Submap.hs
> +-- > flipCompare o = case o of
This is `comparing Down`, I think.

2024-05-08 02:49 UTC, geekosaur approved these changes

2024-05-08 06:45 UTC, TheMC47 requested changes
Thank you for your contribution!

2024-05-08 06:45 UTC, TheMC47 commented on XMonad/Actions/Submap.hs
> +-- > visualSubmap def (sortBy (comparing Down))
This looks wrong: it's the wrong function with the wrong parameter order

2024-05-09 06:27 UTC, merged

2024-05-09 06:27 UTC, slotThe commented
Thanks! :tada: